version: '3.8'

services:
  db:
    image: postgres:15
    container_name: taskmanagement_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=taskmanagementdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    container_name: taskmanagement_api
    build:
      context: .
      dockerfile: TaskManagement.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=taskmanagementdb;Username=user;Password=password;"
    depends_on:
      - db

volumes:
  postgres_data: